# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: ubuntu-20.04
  tools:
    python: mambaforge-4.10

conda:
  environment: environment.yml
  jobs:
    post_build:
      - pip install aiida-vibroscopy

python:
  install:
      - method: pip
        path: .
        extra_requirements:
          - docs

sphinx:
  configuration: tutorial/conf.py
  # fail_on_warning: true
