# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: ubuntu-20.04
  tools:
    python: mambaforge-4.10
  # commands:
  #   - conda init bash
  #   - source ~/.bashrc
  #   - conda activate aiida-vibroscopy-demo
  #   - pip install aiida-vibroscopy[docs]
  #   - pip install git+https://github.com/executablebooks/MyST-NB.git
  #   - sphinx-build -nW --keep-going -b html tutorial _readthedocs/html

conda:
  environment: environment.yml

sphinx:
  configuration: tutorial/conf.py
  fail_on_warning: true
